# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript pr:

# Azure Pipelines YAML for PRs to master branch only

pr:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: npm audit || true
    displayName: 'Check the modules for vulnerabilities'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - script: |
      docker build -t abhishekarora099/myapp-frontend:latest . -f Dockerfile
    displayName: 'Build container image'

  - script: |
      docker run -d abhishekarora099/myapp-frontend:latest
    displayName: 'Run the application'

  - script: docker ps
    displayName: 'Verify container is running'

  - task: Docker@2
    inputs: 
      containerRegistry: dockerhub
      repository: abhishekarora099/myapp-frontend
      command: 'push'
      tags: 'latest'

  - task: Kubernetes@1
    inputs: 
      connectionType: 'Kubernetes Service Connection'
      namespace: default
      command: 'apply'
      arguments: -f k8s/simple
      kubernetesServiceEndpoint: 'gke-dev'

  - script: |
      sleep 60
    displayName: 'wait for LoadBalancer to come up'
    

  - task: Kubernetes@1
    inputs: 
      connectionType: 'Kubernetes Service Connection'
      namespace: default
      command: 'get'
      arguments: service coit-frontend-lb
      kubernetesServiceEndpoint: 'gke-dev'
