apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: mydbconfig
          configMap:
            name: my-db-configs
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: mydbconfig
              mountPath: /etc/config

